[package]
name = "azul_python_engine"
version = "0.1.0"
authors = ["dom_foy <petermccallauway@hotmail.fr>"]
edition = "2018"

[lib]
name = "azul_python_engine"
crate-type = ["cdylib"]
doctest = false
bench = false

[dependencies]
